### ISSUE TITLE
not working in windows

### ISSUE THREAD

**Issue by ofirmgr** [ofirmgr/anyconnect-vpn-tester#1]

**Comment by eliavs** [comment]
I tried running on windows and this is my output:
"C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\jbr\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\lib\idea_rt.jar=55985:C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\es576s\Documents\anyconnect_vpn\out\production\anyconnect_vpn;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\plugins\Kotlin\kotlinc\lib\kotlin-stdlib.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\plugins\Kotlin\kotlinc\lib\kotlin-reflect.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\plugins\Kotlin\kotlinc\lib\kotlin-test.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\plugins\Kotlin\kotlinc\lib\kotlin-stdlib-jdk7.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.4\plugins\Kotlin\kotlinc\lib\kotlin-stdlib-jdk8.jar" ofirmgr.kotlin.xml.dom.TesterKt
FILE: .idea\codeStyles\codeStyleConfig.xml
FILE: .idea\codeStyles\Project.xml
FILE: .idea\kotlinc.xml
FILE: .idea\libraries\KotlinJavaRuntime.xml
FILE: .idea\misc.xml
FILE: .idea\modules.xml
FILE: .idea\vcs.xml
FILE: .idea\workspace.xml
--------------------------
bestName: 
bestTime: 1.7976931348623157E308

Process finished with exit code 0

**Comment by ofirmgr** [comment]
fixed
